import src.model.cnn
import src.model.vit

from .models import create_cnn_score_reg_model
from .models import create_cnn_meta_multitask_reg_model
from .models import create_vit_meta_multitask_reg_model
from .models import create_vit_score_reg_by_cls_model
from .models import create_vit_meta_tag_character_multitask_reg_model
from .models import create_cnn_meta_multitask_transformer_reg_model
from .models import create_cnn_score_classification_model
from .models import create_cnn_rating_classification_model
from .models import create_vit_rating_classification_model
from .models import create_cnn_ai_classification_model