import src.model.cnn
import src.model.vit

from .models import create_cnn_score_reg_model
from .models import create_cnn_meta_multitask_reg_model
from .models import create_vit_meta_multitask_reg_model
from .models import create_vit_score_reg_by_cls_model
from .models import create_vit_meta_tag_character_multitask_reg_model
from .models import create_cnn_meta_multitask_transformer_reg_model
from .models import create_cnn_score_classification_model
from .models import create_cnn_rating_classification_model
from .models import create_vit_rating_classification_model
from .models import create_cnn_ai_classification_model
from .models import create_cnn_transformer_ai_classification_model
from .models import create_cnn_manual_score_classification_model
from .models import create_cnn_manual_score_classification_model_v2
from .models import create_cnn_manual_score_classification_model_v3
from .models import create_cnn_manual_score_classification_model_v4
from .models import create_cnn_manual_score_classification_model_v5
from .models import create_cnn_manual_score_classification_model_v6
from .models import create_cnn_manual_score_classification_multi_task_model_v1
from .models import create_cnn_manual_score_regression_multi_task_model_v1

from .models import create_cnn_transformer_sanity_level_classification_model
from .models import create_cnn_sanity_level_classification_model

from .models import create_cnn_quality_binary_classification_model
from .models import create_vit_quality_binary_classification_model
from .models import create_cnn_transformer_quality_binary_classification_model